name: Build and Publish Docker Images

on:
  push:
    branches:
      - master  # Adjust branch as neededd

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile: ['Dockerfile.cpu', 'Dockerfile.cuda', 'Dockerfile.rocm']
        image-name: ['ff-nsfw_cpu', 'ff-nsfw_cuda', 'ff-nsfw_rocm']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image-name }}:latest
